apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argocd
  labels:
    app: backend
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-weight: "2"
spec:
  selector:
    app: backend
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
